version: '3.4'
services:
  dev:
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: "/ml"
    environment:
      - "GOOGLE_CREDENTIALS=/key.json"
    volumes:
      - "./:/ml"
      - "~/keys/personal-172200.json:/key.json"
  apply:
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: "/ml"
    command: "terraform apply"
    environment:
      - "GOOGLE_CREDENTIALS=/key.json"
    volumes:
      - "./:/ml"
      - "~/keys/personal-172200.json:/key.json"
